#!/usr/bin/env bash
set -euo pipefail

region_id="${1:-}"
position="${2:-}"
prod="${3:-}"

if [ -z "$region_id" ] || [ -z "$position" ]; then
  echo "Usage: publish <region_id> <position> [--prod]"
  exit 1
fi

echo "region_id: $region_id position: $position"

./touristdb generate -id "$region_id" -v

python postprocess/vertices.py generated/"$region_id"/data.json

./touristdb compress -id "$region_id" --verbose

echo "y" | ./touristdb upload -id "$region_id" --position "$position"  "$prod"
