#!/usr/bin/env bash
set -euo pipefail

region_id="${1:-}"
language="${2:-}"
position="${3:-}"
prod="${4:-}"

if [ -z "$region_id" ] || [ -z "$language" ] || [ -z "$position" ]; then
  echo "Usage: publish <region_id> <language> <position> [--prod]"
  exit 1
fi

echo "region_id: $region_id, language: $language, position: $position"

./touristdb generate -id "$region_id" --language "$language" -v

./touristdb compress -id "$region_id" --verbose

echo "y" | ./touristdb upload -id "$region_id" --language "$language" --position "$position"  "$prod"
